<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="RecipeBook.Api.Tests/**/*.cs" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.12">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.12" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    </ItemGroup>
    
    <ItemGroup>
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\appsettings.Development.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\appsettings.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\MvcTestingAppManifest.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests.deps.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\appsettings.Development.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\appsettings.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\MvcTestingAppManifest.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests.deps.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\appsettings.Development.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\appsettings.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\MvcTestingAppManifest.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests.deps.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\appsettings.Development.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\appsettings.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\MvcTestingAppManifest.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests.deps.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\Debug\net8.0\MvcTestingAppManifest.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\Debug\net8.0\RecipeBook.Api.Tests.sourcelink.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\project.assets.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\project.packagespec.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\RecipeBook.Api.Tests.csproj.nuget.dgspec.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.deps.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.staticwebassets.endpoints.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\Debug\net8.0\MvcTestingAppManifest.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\Debug\net8.0\RecipeBook.Api.Tests.sourcelink.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\project.assets.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\project.packagespec.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\RecipeBook.Api.Tests.csproj.nuget.dgspec.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.deps.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.staticwebassets.endpoints.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\Debug\net8.0\MvcTestingAppManifest.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\Debug\net8.0\RecipeBook.Api.Tests.sourcelink.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\project.assets.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\project.packagespec.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\RecipeBook.Api.Tests.csproj.nuget.dgspec.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.deps.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.staticwebassets.endpoints.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\Debug\net8.0\MvcTestingAppManifest.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\Debug\net8.0\RecipeBook.Api.Tests.sourcelink.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\project.assets.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\project.packagespec.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.Api.Tests\obj\RecipeBook.Api.Tests.csproj.nuget.dgspec.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.deps.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.runtimeconfig.json" />
      <_ContentIncludedByDefault Remove="RecipeBook.Api.Tests\bin\Debug\net8.0\RecipeBook.staticwebassets.endpoints.json" />
    </ItemGroup>
</Project>
